<?php
namespace App\Test\TestCase\View\Helper;

use App\View\Helper\ProgressHelper;
use Cake\TestSuite\TestCase;
use Cake\View\View;

class ProgressHelperTest extends TestCase{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $view = new View();
        $this->Progress = new ProgressHelper($view);
    }
    public function testBar(){
        $result = $this->Progress->bar(90);
        $this->assertContains('width: 90%', $result);
        $this->assertContains('progress-bar', $result);
        $this->assertContains('b', $result);
        $this->assertContains('progress-container', $result);
        //$this->assertContains('width 90%', $result);
    }
    
    public function testValue(){
        $this->assertEquals(30, $this->Progress->value(30));
    }
    
    public function testEchoCheck(){
        $this->assertContains('echo statement', $this->Progress->echoCheck());
    }
    
    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}