<?php
namespace App\Test\TestCase\Model\Table;

use Cake\ORM\TableRegistry;
use Cake\TestSuite\TestCase;

class ArticlesTableTest extends TestCase{
    public $fixtures = ['app.articles'];
    
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->Articles = TableRegistry::get('Articles');
    }
    public function testFindPublished(){
        $query = $this->Articles->find()->select(['id', 'title']);
        $this->assertInstanceOf('Cake\ORM\Query', $query);
        $result = $query->hydrate(false)->toArray();
        $expected = [
            ['id' => 1, 'title' => 'First Article'],
            ['id' => 2, 'title' => 'Second Article']
        ];
        $this->assertEquals($expected, $result);
    }
}