<?php
namespace App\Test\TestCase\Controller;

//use Cake\ORM\TableRegistry;
use Cake\TestSuite\IntegrationTestCase;

class ArticlesControllerTest extends IntegrationTestCase{
    public $fixtures = ['app.articles'];
    
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        //$this->Articles = TableRegistry::get('Articles');
    }

    public function testIndex(){
        $this->get('/articles');
        $this->assertResponseOk();
    }
    
    public function testIndexQueryData(){
        $this->get('/articles?page=1');
        $this->assertResponseOk();
        //$this->markTestIncomplete('incomplete');
    }
    
    public function testIndexShort(){
        $this->get('/articles/index/short');
        $this->assertResponseOk();
        $this->assertResponseContains('Articles');
    }
    
    /*public function testIndexPostData(){
        $data = [
            'title' => 'New Article',
            'body' => 'New Body'
        ];
        $this->post('/articles', $data);
        
        $this->assertResponseSuccess();
        $articles = TableRegistry::get('Articles');
        $query = $articles->find()->where(['title' => $data['title']]);
        $this->assertEquals(1, $query->count());
    }*/
    
    public function testAdd(){
        $data = [
            'title' => 'Second Article',
            'body' => 'Second Article body',
            'created' => '2016-09-29 00:00:00'
        ];
        $this->post('/articles/add', $data);
        $this->assertResponseSuccess();
        $this->assertRedirect(['controller' => 'Articles', 'action' => 'index']);
        $this->assertRedirectContains('/articles');
    }

    public function testView(){
        $this->get('/articles/view/1');
        $this->assertResponseSuccess();
    }
    
    public function testDelete(){
        //$article = $this->Articles->get(1);
        //echo $article;
        $this->post('/articles/delete/1', ['id' => 1]);
        $this->assertResponseSuccess();
        //$this->assertRedirect(['controller' => 'Articles', 'action' => 'add']);
    }

    public function testEdit(){
        $this->post('/articles/edit/1', ['id' => 1]);
        $this->assertResponseSuccess();
        $this->assertResponseCode(200);
        //$this->assertRedirect(['controller' => 'Articles', 'action' => 'index']);
    }
}